### ISSUE TITLE
Media information not being updated properly

### ISSUE THREAD

**Issue by jpujol** [aullman/opentok-meet#102]
![screenshot from 2015-09-17 16 04 54](https://cloud.githubusercontent.com/assets/2039799/9948225/22820160-5d56-11e5-9cfb-c7871debd8f1.png)

As you can see, I had HD for almost a minute, but the icon showing the info still was showing 320x240. Also, bitrate info was not correct. Bitrate or packet loss info seemed frozen

**Comment by aullman** [comment]
@jpujol were there any errors in the console? My guess is that there was some kind of error happening which was stopping it from updating at all.

**Comment by jpujol** [comment]
Uncaught TypeError: Cannot read property 'packetsReceived' of undefined
