### ISSUE TITLE
Write a contribution guide

### ISSUE THREAD

**Issue by snobear** [aullman/opentok-meet#107]
Hi,

We are interested in contributing our dev resources to this awesome project, instead of completely forking for our own use.  I was looking at #105 and I liked how they kept the feature in the PR as separate as possible from the core code.  I think it would be beneficial to add some sort of plugin/hook architecture to opentok-meet, so people can easily build new apps and turn on/off features, e.g. #25 for authentication.  Thoughts and suggestions on any node frameworks out there that handle this?

Also, do you have any contribution guide or style specs to conform to?  We can help author that stuff up if you're interested.

**Comment by aoberoi** [comment]
@snobear :clap:

**Comment by aullman** [comment]
Great to hear @snobear. I would love to have you guys collaborate on this project. I agree, the plugin model will make things easier, @ggarber's approach with #105 kind of solves the server side. I don't know of any node frameworks for this kind of thing but haven't looked into it. I'm open to suggestions.

For client-side code I think that splitting out Services and Directives will make it easier on the client-side but I haven't done a whole lot of thinking about it. The SubscriberStats service and directive is a good example of keeping all the functionality separate: https://github.com/aullman/opentok-meet/blob/master/public/js/subscriber-stats.js Also the ot-whiteboard and ot-editor modules are good examples.

As for contribution guides there's our [TokBox Style Guide](https://github.com/opentok/javascript) which is based on AirBnB's guide. This project is using a version of the jshint rules from that repo but I actually want to move over to using the [eslint rules](https://github.com/opentok/javascript/blob/master/linters/eslintrc). I should update the README with contribution guidelines though.

**Comment by snobear** [comment]
Sounds great @aullman.  I'm hoping to combine efforts, but it may not happen if the decision makers on our project want everything done as fast as possible.  Either way, I will check out the style guide and we will make contributions when possible. This is kind of an open-ended discussion thing, so feel free to close this issue or change to something more specific.

**Comment by aullman** [comment]
Let's turn it into a ticket for me to add a contribution guide :)

**Comment by snobear** [comment]
Brilliant!!

**Comment by satyanarayanaAmzur** [comment]
hi friends if any one willing to help me with opentok-Editor related issue, please check this issue
aullman/opentok-editor#6

**Comment by satyanarayanaAmzur** [comment]
https://github.com/aullman/opentok-editor/issues/6
