### ISSUE TITLE
Room appears empty if additional users join with camera disabled

### ISSUE THREAD

**Issue by snobear** [aullman/opentok-meet#109]
Not sure if this occurs with more than two users in the scenario, but anyway heres steps to reproduce with two:
1. User 1 connects to https://meet.tokbox.com/test123 from Chrome and allows camera and mic when prompted by browser.
2. User 2 connects to https://meet.tokbox.com/test123 from Chrome on a different computer and chooses to NOT share camera and mic when prompted by the browser.
3. User 1 still sees "Waiting for someone to join https://speedface.me/testing".
   I do see that the user counter in the bottom left-hand corner updates, but the "Waiting" message remains.

Expected: Waiting box goes away and default "no camera feed" user image is shown.

**Comment by aullman** [comment]
If you click the deny button it denies access to both the camera and the microphone so there is no stream at all. The default no camera feed comes if you have no camera but you do have a microphone. I don't think it makes sense to take up space in the UI for participants that aren't communicating at all. What if you want to have 25 people just watching a presentation that 1 person is giving? 

WDYT?

**Comment by snobear** [comment]
Yes that all makes sense. I agree that having a bunch of "nobody" user images all over the room would be stupid and take up space.  

The specific use case is that we had someone who just wanted to use screen sharing to do a presentation for another person. They sat there waiting for them to join but saw "Waiting for someone to join" even after the other party had joined, and I guess they didn't notice the counter on the left hand bottom corner. 

So this use case is more of a broadcast/presenter situation.l, where people come to watch but not participate.

I think closing/hiding the "Waiting for someone" dialog would be a possible solution, and/or making the users present counter more visible in some way? Perhaps indicate who is not sharing anything as well. Thoughts?

**Comment by aullman** [comment]
Yeah, I have run into that issue before actually as well. I'm fine with making the dialog disappear when anyone joins, not just when they start streaming.
