### ISSUE TITLE
Microphone is not working using Firefox Version 42.0,

### ISSUE THREAD

**Issue by gustavomartin** [aullman/opentok-meet#110]
I tried to use meet.tokbox.com via Firefox but microphone doesn't work, as you could see in attached image. If I use Chrome it works.

![image](https://cloud.githubusercontent.com/assets/2069871/11444650/1929981e-9526-11e5-9da0-d288ecc9f662.png)

If you need extra information, do not hesitate to contact me.

Good Job, your service is amazing.

**Comment by aullman** [comment]
Thanks @gustavomartin. Is this also an issue with other WebRTC services? eg. https://talky.io/ or https://appear.in/

**Comment by aullman** [comment]
Closing this issue because of lack of information. @gustavomartin please reopen and provide more information if you have it.
