### ISSUE TITLE
MS Edge is not Opentok WebRPC-compatible

### ISSUE THREAD

**Issue by ristokorpela** [aullman/opentok-meet#115]
Hi,
just tried to use Edge with your testing environment meet.opentok.com and does not work.

Gives a popup:
*********************
Incompatible Browser

The video component of this application is powered by OpenTok on WebRTC. To enable this functionality, please use Google Chrome or Firefox.
**********************
How this can be possible?

Br, Risto Korpela

**Comment by aullman** [comment]
opentok doesn't support the Edge Browser yet. https://support.tokbox.com/hc/en-us/community/posts/203920933-Microsoft-Edge-Support-When-
