### ISSUE TITLE
Whiteboard broken

### ISSUE THREAD

**Issue by aoberoi** [aullman/opentok-meet#118]
I just tried using the whiteboard for a room on my iPad and it didn't work. The page was served, I saw the browser unsupported message, hit the close button and then just had a blank page. All touches were not even interpreted as scroll (swipe) gestures.

**Comment by aullman** [comment]
Ah yes, this is an issue with Signaling not working in Safari anymore. It used to work but I had to point to v2.6 to get it to work. It works on https://opentok-meet.herokuapp.com 

I filed an issue with OpenTok https://tokbox.atlassian.net/browse/OPENTOK-28440
