### ISSUE TITLE
commons.min.js and login.bundle.min.js?

### ISSUE THREAD

**Issue by athen66** [aullman/opentok-meet#126]
Am I missing something? These files are referenced on the main index page but not seeing it anywhere in the dist:

&lt;script src="/js/commons.min.js" type="text/javascript" charset="utf-8">&lt;/script>
&lt;script src="/js/login.bundle.min.js" type="text/javascript" charset="utf-8">&lt;/script>

**Comment by aullman** [comment]
They are built as part of the build process. The postinstall script runs webpack which bundles those files together. The details are in https://github.com/aullman/opentok-meet/blob/master/webpack.config.js
