### ISSUE TITLE
Module 'opentok-meet' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

### ISSUE THREAD

**Issue by phanthinh** [aullman/opentok-meet#129]
Hi all

I have install then saw error bellow:
![screen shot 2016-07-25 at 4 01 05 pm](https://cloud.githubusercontent.com/assets/5910795/17095920/10e91b84-5281-11e6-875d-2636fd6385eb.png)

Can you help me for this?

Regards,
Phan Thinh

**Comment by aullman** [comment]
I just ran through the installation from scratch again to make sure that things are working and it all looks OK to me. Are you using the master branch? Did you make any changes?

**Comment by aullman** [comment]
Closing this issue because I haven't heard from you. Let me know if you still need help.
