### ISSUE TITLE
When the publisher fails you should know about it

### ISSUE THREAD

**Issue by aullman** [aullman/opentok-meet#132]
Right now if you get a publisher failure you don't know, the publisher just sits there. We should surface an error message if this happens.

**Comment by gblachonupg** [comment]
Hi, I would like to do that, could you give me some tips about where to look for.

Thank you

**Comment by aullman** [comment]
@gblachonupg sure. There is an ["otPublisherError"](https://github.com/aullman/opentok-angular#events) you can listen for and then just surface the error.message to the user. I would suggest adding another element to the [statusMessages](https://github.com/aullman/opentok-meet/blob/master/views/room.ejs#L103).

**Comment by aullman** [comment]
@gblachonupg did you have any luck? If not I'm going to tackle this one. I had another issue today where I failed to publish and didn't notice for about 10 mins that no one in the meeting could see me.

**Comment by gblachonupg** [comment]
Hi, 

I tried this ,

```
        $scope.$on('otPublisherError', function(event, error, publisher) {
          if (publisher.id !== 'screenPublisher') {
            $scope.publishError = true;
          }
        });
```

Added in the controller.

In my view, as you said i added a message to the statusMessage,

```
            <div id="publishStatus" class="statusMessage" ng-if="publishError">
                Error blablabla...
            </div>
```

I think it should work like this.

**Comment by aullman** [comment]
@gblachonupg sorry just saw your response. I already started working on a fix and it's merged in now.
