### ISSUE TITLE
Make an electron app

### ISSUE THREAD

**Issue by gblachonupg** [aullman/opentok-meet#136]
Hello, i try to make an electron app (http://electron.atom.io/) with the project but i get a problem about screensharing.

I use elctron API to get a blob url of the screenshare but i can't publish this stream with OTPublisher because i must use "screen" or "camera" parameter. 

Do you have an idea about how to publish a custom url stream with opentok or where i should look for ?

Thank you  very much

**Comment by aullman** [comment]
Oh, good question. I have never tried to publish a screen from an electron app. You might be able to set the constraints yourself. I believe if you pass a constraints property to OT.initPublisher it will be passed directly to getUserMedia. eg.

```javascript
OT.initPublisher(element, {
  constraints: {
        audio: false,
        video: {
          mandatory: {
            chromeMediaSource: source,
            chromeMediaSourceId: sourceId,
            maxWidth: screen.width,
            maxHeight: screen.height,
            minFrameRate: 1,
            maxFrameRate: 5
          },
          optional: []
        }
});
```

So for this app you would just modify the screen publish props in https://github.com/aullman/opentok-meet/blob/master/src/js/screen/controller.js#L8 to include the constraints.

Let me know if that doesn't work. I'd also be interested if you wanted to contribute back to this project the work you did to build an electron app.

**Comment by gblachonupg** [comment]
Thank you for your answer, i'll tell you how it works 👍 

I tried to init a publisher with the following constraints but it doesn't work :
OT.initPublisher(element, {
  constraints = {
     audio: false,
     video: {
	mandatory: {
        chromeMediaSource: "desktop",
        chromeMediaSourceId: "screen:0:0",
        maxWidth: 960,
        maxHeight: 1706,
        minFrameRate: 1,
        maxFrameRate: 5
    },
    optional: []
  }
});
The constraints do not seem to be passed to getUserMedia, only my camera is used in the publisher.

**Comment by aullman** [comment]
Do those constraints work when you use `getUserMedia` directly?

**Comment by gblachonupg** [comment]
I get back this MediaStream object :
MediaStream {
	id: "Kfpj7i5hBDpk6vIUeQj5pEEQAPpzjHLdbInI",
	active: true,
	onactive: null,
	oninactive: null,
	onended: null,
	oninactive:null,
	onremovetrack:null
}

Seems to work

**Comment by aullman** [comment]
DId you try attaching that media stream to a video element? Also, where did you get the sourceId from? Did you use the desktopCapturer getSources method like here?
https://github.com/electron/electron/blob/master/docs/api/desktop-capturer.md

**Comment by gblachonupg** [comment]
Yes I get the sourceId from the desktop capturer API. I can attach the media stream to a video element with success but I don't understand how I can publish that stream with OpenTok.

**Comment by aullman** [comment]
Yeah, sorry, I was just trying to make sure that those constraints were working without OpenTok. I'm surprised they don't work with the Publisher. Do you have some code I can look at to try to debug it?

**Comment by gblachonupg** [comment]
I just added a sample project here where you can see the problem : https://github.com/gblachonupg/electron-screenshare-opentok/tree/master

**Comment by aullman** [comment]
Aha, you're just missing the constraints part. I submitted a PR
https://github.com/gblachonupg/electron-screenshare-opentok/pull/1

**Comment by gblachonupg** [comment]
Hi,

This worked perfectly, i'll try to add my electron app code when i can.

Thank you very much

**Comment by masudhossain** [comment]
I realize this is a very old thread, but I noticed that what @aullman  posted had a `minFrameRate: 1` and a `maxFrameRate: 5` for the video quality settings. I'm guessing if you have a minFrameRate of 30, it will require the user to screen share at a minimum of 30fps, correct?

Does the minFrameRate only apply to Electron or is this available on all tokbox too, such as this repo: https://github.com/aullman/opentok-meet
