### ISSUE TITLE
Trigger a web notification when someone joins the room and the window is not focused

### ISSUE THREAD

**Issue by aullman** [aullman/opentok-meet#150]
This was suggested by @jraoult. The issue is sometimes you're sitting in an empty room waiting for someone to join and then someone shows up and you don't realise. So the idea is to trigger a web notification when this happens so that you notice.

**Comment by jraoult** [comment]
This jraoult looks like à smart guy :) Happy to tackle it during the next hackday

**Comment by jraoult** [comment]
Ok my bad, so you actually did it :) cool

**Comment by aullman** [comment]
Yep :) Jackie is out tonight and I was feeling inspired.

Keep the ideas coming though and happy for you to contribute next hackday!

**Comment by jraoult** [comment]
Hey juste had a look at the code. What about using notification based on service workers instead: https://github.com/Nickersoft/push.js/blob/master/README.md ? They work on Android mobile (the regular notification don't) and are richer in terms of configuration. They seem to be the way to go forward.

**Comment by aullman** [comment]
Interesting, it looks like that library tries to use a normal Notification and if it catches an exception then it uses serviceworkers. Do you know what that's about?
https://github.com/Nickersoft/push.js/blob/master/push.js#L184

**Comment by jraoult** [comment]
Long story short. Notification constructor doesn't exists in mobile browser where push notifications have to be used instead. It is a matter of lifecycle of apps. Happy to elaborate offline :)

**Comment by aullman** [comment]
Ah, makes sense. Yeah, it would be easy to use push.js instead, good call, thanks.

**Comment by aullman** [comment]
Also clicking on the notification should bring you back to the application.

**Comment by aullman** [comment]
Also we don't need multiple notifications, only one. If more and more people keep joining you don't need to keep popping up notifications.

**Comment by jraoult** [comment]
> Also we don't need multiple notifications, only one. If more and more people keep joining you don't need to keep popping up notifications.

You can probably use (push) notifications tag property for that: https://developer.mozilla.org/en-US/docs/Web/API/Notification/tag

Another nice gesture in terms of usability for users would be to aver a switch to turn off/on notification: https://developers.google.com/web/fundamentals/engage-and-retain/push-notifications/permissions-subscriptions

**Comment by aullman** [comment]
Also I shouldn't trigger a notification if it's your own connectionCreated event 😬
