### ISSUE TITLE
Screensharing does not work while inside iFrame

### ISSUE THREAD

**Issue by masudhossain** [aullman/opentok-meet#158]
Putting in the meeting room inside an iframe will result in errors when trying to share screen. This was working half correct a few days ago (would allow you to at least select which screen you wanted to share). 

example: `<iframe src="https://opentok-meet.herokuapp.com/abcd"></iframe>`

Error:  http://image.prntscr.com/image/88b58d16ba90414bb9c07f86a817acdd.png

**Comment by aullman** [comment]
I am able to choose the screen and then I get "InvalidStateError: Unknown Error while getting user media"
https://output.jsbin.com/waxini

Have you tried hosting the iframe and the app on the same domain? The screensharing extension is enabled for a particular domain and you may need to host the iframe from that same domain.

**Comment by masudhossain** [comment]
That may be the reason for the error I am recieving. Is there a way to whitelist certain domains? I'm doing some CORS stuff .

**Comment by aullman** [comment]
Are you hosting your own version of this on Heroku? Or you're trying to put opentok-meet.herokuapp.com inside an iframe? If you're hosting your own one then you whitelist your own domain with your own Chrome extension. If you're using opentok-meet.herokuapp.com then that's not what it's intended for.

**Comment by masudhossain** [comment]
I tried both ways. 
I'm currently trying to install the screensharing on my Heroku server (video and all others work so far), but just getting some minor errors when installing it on the [opentok-meet repo version](https://github.com/aullman/opentok-meet) (the one on the [screensharing repo](https://github.com/opentok/screensharing-extensions) worked perfectly). 

Quick question, for my chrome extension to work on the opentok-meet repo, does the extension need to be offically registered with chrome extensions? I realize that for this repo, it doesn't need to be registered. I'm just curious if that's why i'm getting the 

> "You need a Chrome extension to share your screen. Install Screensharing Extension. Once you have installed refresh your browser and click the share screen button again."

 error.

**Comment by aullman** [comment]
Oh sorry, you need to use the old extension. From this commit should work https://github.com/opentok/screensharing-extensions/tree/84711a3032eedea5b391d0d9babb0851d388d725/chrome/ScreenSharing

I should update to use v2 but haven't yet.

**Comment by masudhossain** [comment]
Thanks! Can mark this as resolved now.
