### ISSUE TITLE
Getting an Application Error in Heroku when you visit a room on an iOS device in Safari

### ISSUE THREAD

**Issue by aullman** [aullman/opentok-meet#173]

**Comment by aullman** [comment]
![image](https://cloud.githubusercontent.com/assets/733672/22235806/cf577462-e255-11e6-9243-b2cad1c9f0d6.png)

**Comment by masudhossain** [comment]
Wouldn't this error be normal since iOS safari does not support webRTC, yet?

**Comment by aullman** [comment]
Not this error. There should be a page that shows up saying that it's not supported on your device.
