### ISSUE TITLE
Screensharing doesn't work in application

### ISSUE THREAD

**Issue by AntoineR951** [aullman/opentok-meet#188]
Hi, Screensharing with extension doesn't work in application. It works out application when I run "sreensharing-test.htm".

Application don't recognize extension and it ask me to install it. (the extension key is well populated in config file)

**Comment by arifjaunpur** [comment]
@AntoineR951 Are you able to fix it? Screensharing not working for me as well 

I can see "successfully installed" on console but asking again and again to install extension while extension already installed

**Comment by AntoineR951** [comment]
Yes. search in local files : 

       OT.registerScreenSharingExtension('chrome', '<YOUR_CHROME_EXTENSION_ID>');

and become : 

   OT.registerScreenSharingExtension('chrome', '<YOUR_CHROME_EXTENSION_ID>', 2);

**Comment by arifjaunpur** [comment]
thanks @AntoineR951 working fine after updated
