### ISSUE TITLE
Increase FPS of screensharing 

### ISSUE THREAD

**Issue by masudhossain** [aullman/opentok-meet#201]
Is it possible to increase the FPS of screensharing? It's very laggy right now and I'm curious if it's possible to get it to 30-60FPS similar to Discord (they use WebRTC too, but with Electron).

**Comment by aullman** [comment]
opentok-meet isn't doing anything special with screensharing. It's just using WebRTC screensharing so any lag is likely due to the browser. You should file a bug with the browser vendor. Chrome or Firefox.
