### ISSUE TITLE
Can opentok be self hosted?

### ISSUE THREAD

**Issue by theodotos** [aullman/opentok-meet#214]
Hello,

I've looking at the README.md and it says:

> 1. If you haven't already, sign up for OpenTok.
> ...
> 4. Add your OpenTok apikey and secret to config.json

Why is a token from toxbox needed? Can OpenTok be self-hosted?

**Comment by aullman** [comment]
No, it cannot be self-hosted. It is a paid hosted service https://tokbox.com/developer/

**Comment by theodotos** [comment]
Thank you @aullman
