### ISSUE TITLE
layout issue in mozilla firefox

### ISSUE THREAD

**Issue by aoberoi** [aullman/opentok-meet#36]
a few streams failed to connect and it seemed to throw the whole layout engine off. screenshot provided. the top desktop screen was set to be primary using the stretch button.
![screen shot 2014-05-28 at 8 18 45 pm](https://cloud.githubusercontent.com/assets/494795/3112730/17cc556a-e6c7-11e3-8205-398370559de3.png)

**Comment by aullman** [comment]
I think this should be fixed with the latest opentok. Please reopen if you see issues like this again.
