### ISSUE TITLE
Update the meet.tokbox.com mobile app to use the latest cordova and iOS SDK

### ISSUE THREAD

**Issue by aullman** [aullman/opentok-meet#38]

**Comment by snobear** [comment]
Hi @aullman , I was wondering if the mobile app code is on GitHub as well?  Thanks!

**Comment by aullman** [comment]
There are a few different mobile apps around the place that interoperate with meet.tokbox.com

1. https://github.com/opentok/OpenTokRTC-iOS and https://github.com/opentok/OpenTokRTC-Android have been forked and made to work with meet.tokbox.com instead.
2. https://github.com/tokboxnerds/opentok-react-native was built as part of a hackathon project, it is using React-Native.
3. https://github.com/aullman/opentok-meet/tree/master/opentok-meet-cordova this was written 2 years ago and hasn't really been updated in the last year. This issue was referring to this but to be honest it doesn't get much use anymore.

**Comment by snobear** [comment]
@aullman can you point me to the forks mentioned in 1 that work with meet.tokbox.com?  Much apreesh.

**Comment by aullman** [comment]
https://github.com/robjperez/meet-swift
https://github.com/marinaserranomontes/opentok-meet-android

I should add these to the README as well.
