### ISSUE TITLE
hitting backspace in the editor can cause browser to navigate back

### ISSUE THREAD

**Issue by aoberoi** [aullman/opentok-meet#39]
if you place your cursor at the very first character in the editor and then hit backspace, some browsers will navigate back. it also happens if you are just trying to delete everything and are mashing the backspace just to get rid of everything (which is how i found the issue).

on other sites, some pages ask you whether you want to navigate away or not, i'm not sure how thats triggered, but i think that might be appropriate here.

**Comment by aullman** [comment]
Chrome actually removed the backspace to go back feature so this is no longer an issue.
