### ISSUE TITLE
Feature suggestion: Presenter mode

### ISSUE THREAD

**Issue by armandogmendoza** [aullman/opentok-meet#43]
The other day I found that sometimes when somebody is presenting (like during all hands meetings) and there are a 5 or 6 other participants, we observe that the presenter stream struggles to keep up with bitrate because it is competing with the subscriber streams he's seeing as well, 
Would be possible to add new "presenter mode", where the person that is presenting clicks that button and automatically switch all the subscribers into restricted frame rate mode? 
I think that will give us much better experiences in scenarios where there is a high priority stream over the rest.

**Comment by aullman** [comment]
@armandogmendoza it's not exactly a presenter mode but I have added a restrictFrameRate button to each subscriber. Let me know what you think...
