### ISSUE TITLE
add a disclaimer to the UI

### ISSUE THREAD

**Issue by aoberoi** [aullman/opentok-meet#49]
for internal testing use at tokbox, we need to add a small disclaimer to the UI with a message along the lines of "this application is used for testing and stabilization of new platform features, you may also use opentokrtc.com for a similar experience that will not be used for testing"

**Comment by aullman** [comment]
I'm pointing at the production opentok.js right now and so we don't need this disclaimer anymore. If I end up pointing at something experimental again I'll consider adding this.

**Comment by aullman** [comment]
Now that we're pointing at tbdev we should put this in.
