### ISSUE TITLE
Show connected people to notice when somebody is in the session in spy-mode

### ISSUE THREAD

**Issue by ggarber** [aullman/opentok-meet#58]

**Comment by aullman** [comment]
Having a hard time thinking about how to do this and fit it into the UI.

@ggarber what do you think about just a little counter in the corner that tells you how many people are in the room? Or maybe just how many people there are that aren't publishing, so it only shows up if there are people not publishing...

**Comment by aoberoi** [comment]
I think a total number of connections with this icon <http://fortawesome.github.io/Font-Awesome/icon/users/> should be good.

**Comment by aullman** [comment]
Good call. I've been using ionicons so I'll probably use the ionicon people icon http://ionicons.com/

**Comment by ggarber** [comment]
In the short term I think the icon is the simpler solution.
In the mid term I like the opentokrtc approach where you have a chat window where the events are also shown ("xxxx joined the session", "there are 10 people in the session")
this was fast too!

**Comment by aullman** [comment]
@ggarber yes, I've been meaning to add textchat as well. I created #61
