### ISSUE TITLE
Add a textchat component

### ISSUE THREAD

**Issue by aullman** [aullman/opentok-meet#61]

**Comment by aullman** [comment]
I used GoToMeeting recently and they had a growl like interface for TextChat, where even if you weren't looking at the chat it would growl a preview at the top of the page.

**Comment by shorifulislam** [comment]
textchat component is missing.

**Comment by aullman** [comment]
Nobody has started working on it AFAIK.

**Comment by aullman** [comment]
I have started working on https://github.com/aullman/opentok-textchat

I'm open to feedback on the progress so far if anyone has any.

**Comment by shorifulislam** [comment]
When we can aspect "opentok-textchat" component with  opentok-meet?
