### ISSUE TITLE
Add a screenshare only page

### ISSUE THREAD

**Issue by aullman** [aullman/opentok-meet#64]
If you are eg. in a meeting room that is already connected to meet and you just want to share your screen it would be nice to have a dedicated page that just does screensharing without subscribing to anyone or publishing your audio/face. It could be at /{room}/screen like the existing /{room}/whiteboard

Need to figure out how to make this discoverable as well. Also the dedicated whiteboard page should be more discoverable too /{room}/whiteboard...

**Comment by ggarber** [comment]
+1, I do that all the time

**Comment by ggarber** [comment]
Maybe you can add the concept of views/mode to meet.  Presenter /  External Whiteboard / Broadcast ...
