### ISSUE TITLE
Make hidden features more discoverable

### ISSUE THREAD

**Issue by aullman** [aullman/opentok-meet#69]
Need to figure out how to make some of the hidden features more discoverable. Namely:
- Screenshare only pages /:room/screen
- Whiteboard only pages /:room/whiteboard
- How to use p2p (put p2p in the roomname)

**Comment by aoberoi** [comment]
Should we refer to it as p2p or instead use relayed?

**Comment by aullman** [comment]
I called this p2p before we changed it to relayed. I like p2p because it's 3 characters and you're unlikely to put it in your room name by mistake. WDYT?
