### ISSUE TITLE
not running with node v0.12.2

### ISSUE THREAD

**Issue by bluenevus** [aullman/opentok-meet#72]
When we try to run it with node v0.12.2, the opentok-meet page runs however, it will not allow a room to be created.  When I go to a direct url with a name, it leaves a screen that says share url however, there is no url shown.  The rest of the features doesn't load also

**Comment by aullman** [comment]
I just tested with node v0.12.2 and everything is working fine for me. Are you sure you have specified your OpenTok APIKey and Secret in the config.json file?
