### ISSUE TITLE
meet.tokbox.com points to broken IE plugin download link.

### ISSUE THREAD

**Issue by davemun** [aullman/opentok-meet#74]
Repro:
1) Use IE (The one true browser)
  1a) Don't have IE plugin installed, or uninstall it
2) Navigate to meet.tokbox.com
3) Receive IE plugin prompt
4) Check EULA box, click download.
5) Webpage sends you to download from https://s3.amazonaws.com/otplugin.tokbox.com/v0.4.0.11/otiePluginMain.msi, which does not exist.

https://s3.amazonaws.com/otplugin.tokbox.com/v0.4.0.10/otiePluginMain.msi does, however.

**Comment by aullman** [comment]
Thanks @davemun. meet.tokbox.com is pointing to the opentok nightly environment and it turns out we weren't properly building and deploying the IE plugin. Looking into it, I'll report back if/when we fix it.

**Comment by aullman** [comment]
This is no longer an issue.
