### ISSUE TITLE
Can't mute publisher on Chrome for Android

### ISSUE THREAD

**Issue by aullman** [aullman/opentok-meet#76]
From User:

> I earlier tried meet.tokbox.com/in chrome on my note 4. Problem here was that the microphone icon appeared over the video of my face for about 2 second then disappeared meaning I could not mute my call which for a mobile device makes it pretty difficult to avoid background noise destroying a call.

**Comment by aoberoi** [comment]
This issue could be extended to address all the UI controls which appears on hover. Some mobile responsive strategy should be employed (toggle controls on tap?).

**Comment by aullman** [comment]
@aoberoi all of the other controls toggle on tap from my testing...

**Comment by aoberoi** [comment]
what if i don't notice the controls after they fade out? yes it comes up on tap, but i would argue that its not very intuitive, and i have no idea i get controls on tap.

**Comment by aullman** [comment]
@aoberoi do you think the controls should come and go on tap? Instead of fading away after a timeout?

I think this is usually how UI works on mobile right? Thinking about video players...

**Comment by aullman** [comment]
I think the issue here is that the opentok controls don't show up because of the dragging functionality of the publisher. I'm just going to add a mute button to the bottom along with the other controls.
