### ISSUE TITLE
Make the packet loss run over a smaller window

### ISSUE THREAD

**Issue by aullman** [aullman/opentok-meet#89]
Jose carlos asked me to make the packet loss run over a window instead of forever.

It would be good to make it maybe while you're mousing over it counts that time.

Although, then it will always say 0 when you first mouse over. You kind of want it to always give the stats for the last 10 seconds or so. Because you will mouse over when you notice that the audio is bad and it will be good to be able to see whether it was caused by packet loss.

**Comment by odivorra** [comment]
@aullman isn't it possible to keep it sampling over time? what is the problem for that? why do you need to just do it when mousing?

**Comment by aullman** [comment]
@odivorra Yep, that's what I would need to do. It's not a problem it's just more than 10 mins to fix :)

**Comment by odivorra** [comment]
ok I see... :-)
