### ISSUE TITLE
Audio mute button gone

### ISSUE THREAD

**Issue by wobbals** [aullman/opentok-meet#94]
Something appears to have broken the audio mute button, making it really hard for me to slack off during meetings.

**Comment by aullman** [comment]
Yep, this was a bug in the js sdk. It will be fixed the next time tbdev deploys.

**Comment by aullman** [comment]
Thanks for filing this

**Comment by aullman** [comment]
This should be fixed for now by 130f9dc91e7c6ffe8bd42a1aece0cfbdaf432bf6.
